# Generated by Django 5.0.3 on 2024-06-15 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_trip_total_seats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='total_Seats',
            field=models.IntegerField(default=34),
        ),
    ]
