# Generated by Django 5.0.3 on 2024-06-15 17:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_trip_total_seats'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
