# Generated by Django 5.0.3 on 2024-06-15 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_bus_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bus',
            name='name',
        ),
    ]
