# Generated by Django 5.0.3 on 2024-06-17 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_bus_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='trip',
            unique_together={('departure_Station', 'departure_Time', 'id_Buses')},
        ),
    ]
