# Generated by Django 5.0.3 on 2024-07-17 03:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_feedback_idbooking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='idBooking',
        ),
        migrations.AddField(
            model_name='feedback',
            name='idTrip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='app.trip'),
        ),
    ]
