# Generated by Django 5.0.3 on 2024-07-20 10:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_remove_feedback_idbooking_feedback_idtrip'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='vehycle_number',
            field=models.CharField(default=django.utils.timezone.now, max_length=8),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bus',
            name='vehicle_Condition',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='bus',
            unique_together={('vehycle_number',)},
        ),
        migrations.AlterUniqueTogether(
            name='user',
            unique_together={('email',)},
        ),
    ]
