# Generated by Django 5.0.3 on 2024-07-31 02:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_bus_vehycle_number_alter_bus_vehicle_condition_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField()),
                ('totalDistance', models.FloatField(max_length=10)),
                ('idDriver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Salary', to='app.driver')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
