"""
Django settings for ManageBusTicketsBooking project.

Generated by 'django-admin startproject' using Django 5.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Thời gian session tồn tại tính bằng giây (ở đây là 6 phút)
SESSION_COOKIE_AGE = 3600

# Xóa session khi đóng trình duyệt
SESSION_EXPIRE_AT_BROWSER_CLOSE = True

SESSION_SAVE_EVERY_REQUEST = True  # Gia hạn thời gian hết hạn session mỗi khi người dùng gửi request mới


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-%a5%yx*m90hc4(3xzq9u_&x_pnb_3ri*&$dm0_@dt*)2mh6wun'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['.vercel.app']


# Application definition
# settings.py

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',

    # 'ckeditor',
    # 'ckeditor_uploader',

    'app',
    'oauth2_provider',

    'social_django',

]

#Send email
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'  # SMTP server của nhà cung cấp email của bạn
EMAIL_PORT = 587  # Cổng SMTP
EMAIL_USE_TLS = True  # Sử dụng TLS
EMAIL_HOST_USER = 'martbus.office@gmail.com'  # Địa chỉ email của bạn
EMAIL_HOST_PASSWORD = 'pvic dqgw rfiy adta'  # Mật khẩu email của bạn
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER



MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

    # #Login with google
    'social_django.middleware.SocialAuthExceptionMiddleware',

    # Update to Error
    # 'app.middleware.CustomErrorMiddleware',

]

ROOT_URLCONF = 'ManageBusTicketsBooking.urls'
import os

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',

                #Login with google
                'social_django.context_processors.backends',

            ],
        },
    },
]

WSGI_APPLICATION = 'ManageBusTicketsBooking.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}
AUTH_USER_MODEL = 'app.User'  


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    # {
    #     'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    # },
    # {
    #     'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    # },
    # {
    #     'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    # },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Ho_Chi_Minh'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

import os

STATIC_URL = 'static/'

MEDIA_ROOT = '%s/app/static/' % BASE_DIR
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'app/static/media')


#Upload của ckEditor = MEDIA_ROOT + CKEDITOR_UPLOAD_PATH
CKEDITOR_UPLOAD_PATH='bus/'


# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'



#Login with google (social app custom settings)
AUTHENTICATION_BACKENDS=[
    'social_core.backends.google.GoogleOAuth2',
    'django.contrib.auth.backends.ModelBackend',

]

LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'home'
LOGOUT_URL ='logout'
LOGOUT_REDIRECT_URL='login'

#Login with google
SOCIAL_AUTH_GOOGLE_OAUTH2_KEY = '298185301392-delrk00209hqf7h34780eebbvj7cjo1e.apps.googleusercontent.com' #10
SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET ='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' #12

